[project]
name = "datathons"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.40",
    "influxdb-client>=1.49.0",
    "moto>=5.1.13",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "pytest>=8.4.2",
]
