name: Auto-merge Documentation PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  auto-merge-docs:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'github-actions[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'automated') &&
      contains(github.event.pull_request.labels.*.name, 'documentation') &&
      contains(github.event.pull_request.labels.*.name, 'auto-merge')
    
    permissions:
      contents: write
      pull-requests: write
      checks: read

    steps:
      - name: Wait for status checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'validate-docs'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Enable auto-merge
        if: success()
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Add approval
        if: success()
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}

      - name: Comment on PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Auto-merge enabled** - This documentation PR will be automatically merged once all checks pass.\n\n✅ Documentation validation completed successfully.'
            })

  notify-failure:
    runs-on: ubuntu-latest
    if: |
      failure() &&
      github.actor == 'github-actions[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'automated') &&
      contains(github.event.pull_request.labels.*.name, 'documentation')
    
    permissions:
      pull-requests: write

    steps:
      - name: Comment on failed PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Auto-merge failed** - Documentation validation checks failed. Please review the errors and fix them manually.\n\n🔍 Check the workflow logs for details on what needs to be fixed.'
            })

      - name: Remove auto-merge label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'auto-merge'
            })